name        : v4l-utils
version     : 1.8.1
release     : 3
source     :
    - http://linuxtv.org/downloads/v4l-utils/v4l-utils-1.8.1.tar.bz2 : 2f6219b03f19ea07c100e860238d5cdbfcbcfe440a14477e75137cc073431b33
license     :
    - GPL-2.0+
summary     : Linux V4L2 and DVB API utilities and v4l libraries 
builddeps   :
    - pkgconfig(x11)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(alsa)
    - pkgconfig(libudev)
    - libjpeg-turbo-devel
description : |
    Linux V4L2 and DVB API utilities and v4l libraries
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install -j1
