name       : v4l-utils
version    : 1.16.2
release    : 9
source     :
    - https://linuxtv.org/downloads/v4l-utils/v4l-utils-1.16.2.tar.bz2 : 6c3208c9a1c73455d30bae83096d161e57bec5008594f270a2a67df8c86d8e47
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.video
summary    : Linux V4L2 and DVB API utilities and v4l libraries
description: |
    Linux utilities and libraries to handle media devices (TV devices, capture devices, radio devices, remote controllers).
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(gl)
    - pkgconfig32(glu)
    - pkgconfig32(libjpeg)
    - pkgconfig32(libudev)
    - pkgconfig32(x11)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install -j1
