name       : v4l-utils
version    : 1.14.2
release    : 7
source     :
    - https://linuxtv.org/downloads/v4l-utils/v4l-utils-1.14.2.tar.bz2 : e6b962c4b1253cf852c31da13fd6b5bb7cbe5aa9e182881aec55123bae680692
license    :
    - GPL-2.0
    - LGPL-2.1
component  : multimedia.video
summary    : Linux V4L2 and DVB API utilities and v4l libraries
description: |
    Linux V4L2 and DVB API utilities and v4l libraries
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(gl)
    - pkgconfig32(glu)
    - pkgconfig32(libjpeg)
    - pkgconfig32(libudev)
    - pkgconfig32(x11)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install -j1
