name       : v4l-utils
version    : 1.12.5
release    : 6
source     :
    - https://linuxtv.org/downloads/v4l-utils/v4l-utils-1.12.5.tar.bz2 : 0618162ddb0b57fe7c45407d4d66ed79e3a134cdbc9e72598d34e61d3359e20d
license    :
    - GPL-2.0
    - LGPL-2.1
component  : multimedia.video
summary    : Linux V4L2 and DVB API utilities and v4l libraries
description: |
    Linux V4L2 and DVB API utilities and v4l libraries
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(gl)
    - pkgconfig32(glu)
    - pkgconfig32(libudev)
    - pkgconfig32(x11)
    - libjpeg-turbo-32bit-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install -j1
