name        : v4l-utils
version     : 1.8.1
release     : 4
source      :
    - http://linuxtv.org/downloads/v4l-utils/v4l-utils-1.8.1.tar.bz2 : 2f6219b03f19ea07c100e860238d5cdbfcbcfe440a14477e75137cc073431b33
license     : GPL-2.0
component   : multimedia.video
summary     : Linux V4L2 and DVB API utilities and v4l libraries 
description : |
    Linux V4L2 and DVB API utilities and v4l libraries
emul32      : yes
builddeps   :
    - pkgconfig32(alsa)
    - pkgconfig32(gl)
    - pkgconfig32(glu)
    - pkgconfig32(libudev)
    - pkgconfig32(x11)
    - libjpeg-turbo-32bit-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install -j1
