name       : v4l-utils
version    : 1.18.0
release    : 11
source     :
    - https://linuxtv.org/downloads/v4l-utils/v4l-utils-1.18.0.tar.bz2 : 6cb60d822eeed20486a03cc23e0fc65956fbc1e85e0c1a7477f68bbd9802880d
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.video
summary    : Linux V4L2 and DVB API utilities and v4l libraries
description: |
    Linux utilities and libraries to handle media devices (TV devices, capture devices, radio devices, remote controllers).
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(gl)
    - pkgconfig32(glu)
    - pkgconfig32(libjpeg)
    - pkgconfig32(libudev)
    - pkgconfig32(x11)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install -j1
